apiVersion: v1
kind: Service
metadata:
  name: swagger-java-app-deployment-service
spec:
  selector:
    app: swagger-java-app-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376